linters:
  enable:
    - cyclop
    - copyloopvar
    - gocritic
    - gofumpt
    - goimports
    - gosec
    - ineffassign
    - misspell
    - prealloc
    - unconvert
    - unparam
    - revive
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/adityasanka/gosort
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  whitespace:
    multi-func: true

issues:
  # The 'exclude-use-default: false' setting under 'issues' means that
  # golangci-lint will not use its default exclusions for issues.
  # By default, golangci-lint excludes certain types of issues
  # (like auto-generated files). Setting this to false ensures
  # that all issues are reported, giving more control to the user
  # but potentially increasing the number of reported issues.
  exclude-use-default: false
