name: Lint
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint:
    name: Lint with golang-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
